name: FUSE Integration CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_call:

defaults:
  run:
    working-directory: vfat-fuse-integration

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt -- --check
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  test:
    name: Build & Test
    needs: [ style, clippy ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dosfstools
        run: sudo apt-get update && sudo apt-get install -y dosfstools

      - name: Build
        run: cargo build --all-targets

      - name: Test
        run: cargo test
